CREATE TABLE  Users  (
	id  VARCHAR(150) NOT NULL,
	email  VARCHAR(150) NOT NULL UNIQUE,
	fullname  VARCHAR(150) NOT NULL,
	password  VARCHAR(500) NOT NULL,
    created_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    companyid  VARCHAR(200) DEFAULT NULL,
	PRIMARY KEY (id),
    FOREIGN KEY (companyid) REFERENCES  Company(id) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE  Company  (
	id  VARCHAR(200) NOT NULL,
	name  VARCHAR(200) NOT NULL UNIQUE,
	ownername  VARCHAR(100) NOT NULL,
	address  VARCHAR(200) NOT NULL,
	city  VARCHAR(200),
	url  VARCHAR(200),
	tel  VARCHAR(50),
    updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    type  VARCHAR(50) NOT NULL,
	PRIMARY KEY (id)
);

