CREATE TABLE  Users  (
	id  VARCHAR(150) NOT NULL,
	email  VARCHAR(150) NOT NULL UNIQUE,
	fullname  VARCHAR(150) NOT NULL,
	password  VARCHAR(500) NOT NULL,
    created_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);

CREATE TABLE  Company  (
	id  VARCHAR(200) NOT NULL,
	name  VARCHAR(200) NOT NULL UNIQUE,
	ownername  VARCHAR(100) NOT NULL,
	address  VARCHAR(200) NOT NULL,
	city  VARCHAR(200),
	url  VARCHAR(200),
	tel  VARCHAR(50),
	type  VARCHAR(50) NOT NULL,
	category  VARCHAR(50) DEFAULT '',
    updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);

CREATE TABLE  Company_User  (
	userid  VARCHAR(200) NOT NULL,
	companyid  VARCHAR(200) NOT NULL,
	PRIMARY KEY (userid, companyid),
	FOREIGN KEY (userid) REFERENCES Users(id) ON DELETE CASCADE,
	FOREIGN KEY (companyid) REFERENCES Company(id) ON DELETE CASCADE
);

CREATE TABLE  Tender  (
	id  VARCHAR(200) NOT NULL,
	ref  VARCHAR(200) NOT NULL,
	title  VARCHAR(200) NOT NULL UNIQUE,
	description  VARCHAR(500) NOT NULL,
	category  VARCHAR(200) NOT NULL,
	location  VARCHAR(200) NOT NULL,
	expirydate  TIMESTAMP NOT NULL,
	created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	companyid  VARCHAR(200),
	image  VARCHAR(200) DEFAULT NULL,
	document  VARCHAR(200) DEFAULT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY (companyid) REFERENCES  Company(id) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE  Bids  (
	id  VARCHAR(200) NOT NULL,
	tenderid  VARCHAR(200) NOT NULL,
	companyid  VARCHAR(200) NOT NULL,
	amount  DECIMAL(10,2) NOT NULL,
	created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (id),
	FOREIGN KEY (tenderid) REFERENCES  Tender(id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (companyid) REFERENCES  Company(id) ON DELETE CASCADE ON UPDATE CASCADE,
	UNIQUE (tenderid, companyid)
);